### ISSUE TITLE
Adblock Puppeteer - Page Error - "Evaluation Failed"

### ISSUE THREAD

**Issue by theninj4** [cliqz-oss/adblocker#1060]
Hey :wave: 

I think I've found a simple bug whereby one of the commands is lacking some error handling:

https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L330:L332
```javascript
          frame.addScriptTag({
            content: autoRemoveScript(scripts[i]),
          })
```

The error bubbles up via `page.on('error', (e) => { })` and looks like this:
```
Error: Evaluation failed: TypeError: Cannot read property 'appendChild' of null
    at addScriptContent (__puppeteer_evaluation_script__:7:27)
    at ExecutionContext._evaluateInternal (/opt/node_modules/puppeteer/lib/ExecutionContext.js:102:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DOMWorld.addScriptTag (/opt/node_modules/puppeteer/lib/DOMWorld.js:183:21)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/opt/node_modules/puppeteer/lib/helper.js:94:19)
    at DOMWorld.addScriptTag (/opt/node_modules/puppeteer/lib/DOMWorld.js:183:35)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/opt/node_modules/puppeteer/lib/helper.js:94:19)
    at PuppeteerBlocker.injectScriptletsIntoFrame (/opt/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:290:37)
    at PuppeteerBlocker.onFrame (/opt/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:151:26)
    at PuppeteerBlocker.onFrameNavigated (/opt/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:112:28)
    at BlockingContext.onFrameNavigated (/opt/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:63:52)
    at Page.<anonymous> (/opt/node_modules/@cliqz/adblocker-puppeteer/dist/cjs/adblocker.js:71:22)
    at Page.emit (events.js:315:20)
    at CDPSession.<anonymous> (/opt/node_modules/puppeteer/lib/Page.js:123:59)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (/opt/node_modules/puppeteer/lib/Connection.js:166:18)
``` 

The docs for `frame.addScriptTag` suggest it returns a promise (https://devdocs.io/puppeteer/). Something like popping an empty catch block on the end resolves the issue:
```javascript
          frame.addScriptTag({
            content: autoRemoveScript(scripts[i]),
          }).catch(e => e),
```

There is a similar issue just a few lines above it (but I don't have a stack trace for this one to hand):
https://github.com/cliqz-oss/adblocker/blob/master/packages/adblocker-puppeteer/adblocker.ts#L315
```javascript
            await frame.addStyleTag({
                content: styles,
            });
```

**Comment by remusao** [comment]
Hi @theninj4,

Good catch, and thank you for taking the time to investigate the root of the issue. I was a bit surprised because as far as I could the promises from `addStyleTag` and `addScriptTag` should have been awaited in a `Promise.all(...)` and a `catch(...)` block was already present. But it seems like there was a bug whereas an array of promises was simply awaited with `await promises` instead of `await Promise.all(promises)`, which I guess was the root of the issue. Interesting that TypeScript did not catch this issue!

I have made a fix here: https://github.com/cliqz-oss/adblocker/pull/1067, could you maybe have a look and see if this looks good to you?

Best,
Rémi
