### ISSUE TITLE
retry on fetch error?

### ISSUE THREAD

**Issue by davalapar** [cliqz-oss/adblocker#390]
```sh
FetchError: request to https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt failed, reason: connect ETIMEDOUT 94.130.73.103:443
    at ClientRequest.<anonymous> (/home/davalapar/cryptoratez/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'request to https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt failed, reason: connect ETIMEDOUT 94.130.73.103:443',
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
```

**Comment by remusao** [comment]
Hi @davalapar,

Good point, I will add a retry mechanism. Thanks for the suggestion.
