### ISSUE TITLE
Disable blocker in electron

### ISSUE THREAD

**Issue by Xanon50rus** [cliqz-oss/adblocker#991]
Hi, how can i dynamically disable blocker in electron app? (I want to make turn on/off button)
Code:
`****
contents.on('did-finish-load', () => {
            ElectronBlocker.fromPrebuiltAdsAndTracking(fetch, {
                path: 'engine.bin',
                read: fs.readFile,
                write: fs.writeFile,
            }).then((blocker) => {
                if (adBlock) {
                    blocker.enableBlockingInSession(session.defaultSession);
                } else {
                    blocker.disableBlockingInSession(session.defaultSession);
                }
            });
        })
***`

But i always have this error:

`(node:25288) UnhandledPromiseRejectionWarning: Error: Trying to disable blocking which was not enabled
[1]     at ElectronBlocker.disableBlockingInSession (C:\electron-browser-react\node_modules\@cliqz\adblocker-electron\dist\cjs\adblocker.js:184:19)
[1]     at C:\electron-browser-react\main.js:97:29
[1] (node:25288) UnhandledPromiseRejectionWarning: Error: Trying to disable blocking which was not enabled
[1]     at ElectronBlocker.disableBlockingInSession (C:\electron-browser-react\node_modules\@cliqz\adblocker-electron\dist\cjs\adblocker.js:184:19)
[1]     at C:\electron-browser-react\main.js:97:29
[1] (node:25288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:25288) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, 
or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[1] (node:25288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[1] (node:25288) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I have Electron+React.

**Comment by remusao** [comment]
Hey @Xanon50rus,

From the code it's not so clear to me in which context you want to enable or disable the adblocker. Are you sure that you are not disabling the adblocker multiple times for the same session?

If you could give some more context about the logic in your program I think it would be useful to diagnose the issue.

Best,

**Comment by Xanon50rus** [comment]
Hey @remusao 
in main file I have variable:
`let adBlock = true;`
And then I toggle it every time when user clicks a button:
`ipcMain.on("adblock-event", (IpcMainEvent, args) => {
    adBlock = !adBlock;
});`
After that user need to reload the page and 'did-finish-load' method will call disable of adblocker, but I have error. I tried to add another variable which checked if adBlocker already disabled but i still got this error.

**Comment by Xanon50rus** [comment]
Hey @remusao thank you so much for help! I solved my problem.
